import Navbar from '@/components/Navbar';
import Provider from '@/components/Provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getSession } from 'next-auth/react';
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <main className=' flex flex-col justify-center items-center'>
          <Navbar />
            {children}
            <Toaster />
          </main>
        </Provider>
      </body>
    </html>
  );
}
